name: Setup Terraform Backend

on:
  workflow_dispatch:

jobs:
  setup-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Create Backend Resources
        run: |
          terraform init
          terraform apply -target=aws_s3_bucket.terraform_state -target=aws_dynamodb_table.terraform_state_lock -auto-approve
          BUCKET_NAME=$(terraform output -raw s3_bucket_name)
          echo "Created bucket: $BUCKET_NAME"
          echo "Manually update provider.tf with this bucket name"